method: conv_adapter

# Adapter of ACCDOA or mACCDOA
adapt_kwargs:
  position: [MlpAdapter, SpatialAdapter] # MlpAdapter or SpatialAdapter or before_msa
  type: linear_adapter # adapter
  mlp_ratio: 0.5
  adapter_scalar: 0.1 # learnable_scalar
  act_layer: 'gelu'

  # 卷积参数
  kernel_size: 3
  padding: 1
  stride: 1
  groups: 1
  dilation: 1
  # norm_layer: nn.LayerNorm
  # act_layer: nn.GELU