# DCT频率适配器配置文件
# 这个配置文件定义了使用频率注意力机制的DCT适配器

method: adapter_dct_freq

adapt_kwargs:
  position: [MlpAdapter,SpatialAdapter]  # 同时在MLP层和注意力层后添加适配器
  type: adapter_frequency
  mlp_ratio: 0.5
  act_layer: gelu
  adapter_scalar: 0.1
