# DCT适配器配置文件
# 这个配置文件定义了使用离散余弦变换增强频率信息的适配器

method: adapter_dct

adapt_kwargs:
  position: [MlpAdapter]  # 同时在MLP层和注意力层后添加适配器
  type: adapter_dct
  mlp_ratio: 0.5
  act_layer: gelu
  adapter_scalar: 0.1
  # 使用真实的T和F参数，避免sqrt(N)的不准确拆分
  # time_steps: 64  # STARSS23数据集的时间步长
  # freq_bins: 1001  # STARSS23数据集的频率分量数