method: wconv_adapter

# Adapter of ACCDOA or mACCDOA
adapt_kwargs:
  position: [MlpAdapter, SpatialAdapter] # MlpAdapter or SpatialAdapter or before_msa
  # type: linear_adapter # adapter
  type: wConvAdapter # adapter
  mlp_ratio: 0.5
  adapter_scalar: 0.1 # learnable_scalar

  # 卷积参数
  kernel_size: 3
  padding: 1
  # padding: 3
  stride: 1
  groups: 16
  # width: 32
  den: [0.5]

  act_layer: 'gelu'