# configs/timefreq_visual.yaml

# 指定默认配置
defaults:
  - hydra: default.yaml
  - logger: tensorboard.yaml
  - paths: default.yaml
  - augment: default.yaml
  - data: default.yaml
  - model: htsat.yaml
  - loss: accdoa.yaml
  - extras: default.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - task: seld.yaml
  - adapt: default.yaml
  - _self_
  
  # 实验配置
  - experiment: starss23_maccdoa # null
  - debug: null

# 任务名称
task_name: ${model.method}_${model.backbone}_expert_activation_visual
experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# 可视化模式：valid(验证) | test(测试)
mode: valid

# 数据加载的工作进程数
num_workers: 8

# 检查点路径（可通过命令行覆盖）
# ckpt_path: /workspace/pycharm_projects/PSELDNets-main/ckpts/visual/AdapterFusion/epoch_039.ckpt
ckpt_path: /workspace/pycharm_projects/PSELDNets-main/ckpts/visual/MixAdapter/epoch_078_se_mona_revise.ckpt

# 随机种子
seed: 2025

# 是否使用PyTorch 2.0的模型编译功能
compile: false

# 时频域适配器可视化配置
visual:
  # 基本设置
  num_samples: 10                 # 分析的batch数量（建议5-15个）  