# 指定默认配置
# 默认配置的顺序决定了配置之间的覆盖顺序
defaults:
  - _self_                      # 当前配置文件
  - hydra: default.yaml         # Hydra基础配置
  - logger: tensorboard.yaml    # 日志记录器配置，也可以通过命令行设置
  - paths: default.yaml         # 路径配置
  - augment: default.yaml       # 数据增强配置
  - data: default.yaml          # 数据集配置
  - model: htsat.yaml          # 模型配置，使用HTSAT模型
  - loss: accdoa.yaml          # 损失函数配置，使用ACCDOA损失
  - adapt: default.yaml         # 适配器配置
  - extras: default.yaml        # 额外配置
  - callbacks: default.yaml     # 回调函数配置
  - trainer: default.yaml       # 训练器配置
  - task: seld.yaml            # 任务配置，SELD任务

  # 实验配置允许对特定超参数进行版本控制
  # 例如：给定模型和数据模块的最佳超参数
  - experiment: null

  # 调试配置（通过命令行启用，例如：`python train.py debug=default`）
  - debug: null

# 任务/实验名称，决定输出目录路径
task_name: ${model.method}_${model.backbone}  # 使用模型方法和骨干网络名称
experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}  # 使用时间戳作为实验名称

# 数据加载的工作进程数
num_workers: 8  # 8 0

# 声音事件检测(SED)的阈值
sed_threshold: 0.5

# 检查点路径，用于恢复训练
ckpt_path: null

# 随机数生成器的种子，用于PyTorch、NumPy和Python.random
seed: 2025

# 是否使用PyTorch 2.0的模型编译功能来加速训练
compile: True